### ISSUE TITLE
rename repository to git-pr?

### ISSUE THREAD

**Issue by rkdarst** [NordicHPC/git-pr#14]
This consists of one script named `git-pr`, but the repository is named `git-pr-tools`.  By now it probably will only consist of one script.

Should we rename the repository to `git-pr` instead?

There already is a project https://github.com/ozh/git-pr, but it is very minimal and not overlapping.  Thoughts?

**Comment by rkdarst** [comment]
Actually ozh/git-pr does a subset of this... using a php script.

**Comment by bast** [comment]
I agree that `git-pr` is probably a better name. Thumbs up for rename. I don't think that the name collision is a problem.

**Comment by rkdarst** [comment]
I did it!  I hope it helps marketing in the end...
